#!/bin/sh
SCRIPTS=`dirname $0`
. ${SCRIPTS}/pax-validate

if [ -z "${PAX_CONSTRUCT_VERSION}" ]
then
  PAX_CONSTRUCT_VERSION=${project.version}
fi

PAX_PLUGIN=org.ops4j.pax.construct:maven-pax-plugin:${PAX_CONSTRUCT_VERSION}

unset FRAMEWORK

while
  getopts f:h- SETTING
do
  case ${SETTING} in
    h|\?) echo "pax-provision [-f framework] [-- mvnOpts ...]" ; exit ;;

    f) FRAMEWORK=${OPTARG} ;;

    -) break ;;
  esac
done

shift $((${OPTIND}-1))

mvn ${PAX_PLUGIN}:provision \
  -Dframework=${FRAMEWORK:=choose} \
  ${PAX_CONSTRUCT_OPTIONS} "$@"

