#!/bin/sh
SCRIPTS=`dirname $0`
. ${SCRIPTS}/pax-validate

if [ -z "${PAX_CONSTRUCT_VERSION}" ]
then
  PAX_CONSTRUCT_VERSION=${project.version}
fi

PAX_PLUGIN=org.ops4j.pax.construct:maven-pax-plugin:${PAX_CONSTRUCT_VERSION}

unset BUNDLENAME

while
  getopts n:h- SETTING
do
  case ${SETTING} in
    h|\?) echo "pax-use-bundle -n bundleName [-- mvnOpts ...]" ; exit ;;

    n) BUNDLENAME=${OPTARG} ;;

    -) break ;;
  esac
done

shift $((${OPTIND}-1))

if [ -z "${BUNDLENAME}" ]
then
  read -p "bundleName (myBundle) ? " BUNDLENAME
fi

mvn ${PAX_PLUGIN}:use-bundle \
  -DbundleName=${BUNDLENAME:=myBundle} \
  ${PAX_CONSTRUCT_OPTIONS} "$@"

