#!/bin/sh
SCRIPTS=`dirname $0`
. ${SCRIPTS}/pax-validate

if [ -z "${PAX_CONSTRUCT_VERSION}" ]
then
  PAX_CONSTRUCT_VERSION=${project.version}
fi

PAX_PLUGIN=org.ops4j.pax.construct:maven-pax-plugin:${PAX_CONSTRUCT_VERSION}

unset BUNDLENAME
unset TARGETDIRECTORY

while
  getopts n:d:h- SETTING
do
  case ${SETTING} in
    h|\?) echo "pax-move-bundle -n bundleName -d targetDirectory [-- mvnOpts ...]" ; exit ;;

    n) BUNDLENAME=${OPTARG} ;;
    d) TARGETDIRECTORY=${OPTARG} ;;

    -) break ;;
  esac
done

shift $((${OPTIND}-1))

if [ -z "${BUNDLENAME}" ]
then
  read -p "bundleName (myBundle) ? " BUNDLENAME
fi
if [ -z "${TARGETDIRECTORY}" ]
then
  read -p "targetDirectory (.) ? " TARGETDIRECTORY
fi

mvn ${PAX_PLUGIN}:move-bundle \
  -DbundleName=${BUNDLENAME:=myBundle} \
  -DtargetDirectory=${TARGETDIRECTORY:=.} \
  ${PAX_CONSTRUCT_OPTIONS} "$@"

