#!/bin/sh
SCRIPTS=`dirname $0`
. ${SCRIPTS}/pax-validate

if [ -z "${PAX_CONSTRUCT_VERSION}" ]
then
  PAX_CONSTRUCT_VERSION=${project.version}
fi

PAX_PLUGIN=org.ops4j.pax.construct:maven-pax-plugin:${PAX_CONSTRUCT_VERSION}

unset GROUPID
unset ARTIFACTID
unset VERSION

while
  getopts g:a:v:h- SETTING
do
  case ${SETTING} in
    h|\?) echo "pax-import-bundle -g groupId -a artifactId -v version [-- mvnOpts ...]" ; exit ;;

    g) GROUPID=${OPTARG} ;;
    a) ARTIFACTID=${OPTARG} ;;
    v) VERSION=${OPTARG} ;;

    -) break ;;
  esac
done

shift $((${OPTIND}-1))

if [ -z "${GROUPID}" ]
then
  read -p "groupId (org.ops4j.example) ? " GROUPID
fi
if [ -z "${ARTIFACTID}" ]
then
  read -p "artifactId (myBundle) ? " ARTIFACTID
fi
if [ -z "${VERSION}" ]
then
  read -p "version (0.1.0-SNAPSHOT) ? " VERSION
fi

mvn ${PAX_PLUGIN}:import-bundle \
  -DgroupId=${GROUPID:=org.ops4j.example} \
  -DartifactId=${ARTIFACTID:=myBundle} \
  -Dversion=${VERSION:=0.1.0-SNAPSHOT} \
  ${PAX_CONSTRUCT_OPTIONS} "$@"

