#!/bin/sh
SCRIPTS=`dirname $0`
. ${SCRIPTS}/pax-validate

if [ -z "${PAX_CONSTRUCT_VERSION}" ]
then
  PAX_CONSTRUCT_VERSION=${project.version}
fi

PAX_PLUGIN=org.ops4j.pax.construct:maven-pax-plugin:${PAX_CONSTRUCT_VERSION}

unset PACKAGE
unset NAME
unset VERSION

while
  getopts p:n:v:h- SETTING
do
  case ${SETTING} in
    h|\?) echo "pax-create-bundle -p javaPackage -n bundleName [-v version ] [-- mvnOpts ...]" ; exit ;;

    p) PACKAGE=${OPTARG} ;;
    n) NAME=${OPTARG} ;;
    v) VERSION=${OPTARG} ;;

    -) break ;;
  esac
done

shift $((${OPTIND}-1))

if [ -z "${PACKAGE}" ] || [ -z "${NAME}" ]
then
  if [ -z "${PACKAGE}" ]
  then
    read -p "java package (org.ops4j.example) ? " PACKAGE
  fi
  if [ -z "${NAME}" ]
  then
    read -p "bundle name (myBundle) ? " NAME
  fi
  if [ -z "${VERSION}" ]
  then
    read -p "bundle version (0.1.0-SNAPSHOT) ? " VERSION
  fi
fi

mvn ${PAX_PLUGIN}:create-bundle \
  -Dpackage=${PACKAGE:=org.ops4j.example} \
  -Dname=${NAME:=myBundle} \
  -Dversion=${VERSION:=0.1.0-SNAPSHOT} \
  ${PAX_CONSTRUCT_OPTIONS} "$@"

