#!/bin/sh
SCRIPTS=`dirname $0`
. ${SCRIPTS}/pax-validate

if [ -z "${PAX_CONSTRUCT_VERSION}" ]
then
  PAX_CONSTRUCT_VERSION=${project.version}
fi

PAX_PLUGIN=org.ops4j.pax.construct:maven-pax-plugin:${PAX_CONSTRUCT_VERSION}

unset NAME

while
  getopts n:h- SETTING
do
  case ${SETTING} in
    h|\?) echo "pax-remove-bundle -n bundleName [-- mvnOpts ...]" ; exit ;;

    n) NAME=${OPTARG} ;;

    -) break ;;
  esac
done

shift $((${OPTIND}-1))

if [ -z "${NAME}" ]
then
  read -p "bundle name (myBundle) ? " NAME
fi

mvn ${PAX_PLUGIN}:remove-bundle \
  -Dname=${NAME:=myBundle} \
  ${PAX_CONSTRUCT_OPTIONS} "$@"

