#!/bin/sh
SCRIPTS=`dirname $0`
. ${SCRIPTS}/pax-validate

if [ -z "${PAX_CONSTRUCT_VERSION}" ]
then
  PAX_CONSTRUCT_VERSION=${project.version}
fi

PAX_PLUGIN=org.ops4j.pax.construct:maven-pax-plugin:${PAX_CONSTRUCT_VERSION}

unset PACKAGE
unset BUNDLENAME
unset VERSION

while
  getopts p:n:v:h- SETTING
do
  case ${SETTING} in
    h|\?) echo "pax-create-bundle -p package -n bundleName [-v version] [-- mvnOpts ...]" ; exit ;;

    p) PACKAGE=${OPTARG} ;;
    n) BUNDLENAME=${OPTARG} ;;
    v) VERSION=${OPTARG} ;;

    -) break ;;
  esac
done

shift $((${OPTIND}-1))

if [ -z "${PACKAGE}" ] || [ -z "${BUNDLENAME}" ]
then
  if [ -z "${PACKAGE}" ]
  then
    read -p "package (org.ops4j.example) ? " PACKAGE
  fi
  if [ -z "${BUNDLENAME}" ]
  then
    read -p "bundleName (myBundle) ? " BUNDLENAME
  fi
  if [ -z "${VERSION}" ]
  then
    read -p "version (0.1.0-SNAPSHOT) ? " VERSION
  fi
fi

mvn ${PAX_PLUGIN}:create-bundle \
  -Dpackage=${PACKAGE:=org.ops4j.example} \
  -DbundleName=${BUNDLENAME:=myBundle} \
  -Dversion=${VERSION:=0.1.0-SNAPSHOT} \
  ${PAX_CONSTRUCT_OPTIONS} "$@"

