#!/bin/sh
SCRIPTS=`dirname $0`
. ${SCRIPTS}/pax-validate

if [ -z "${PAX_CONSTRUCT_VERSION}" ]
then
  PAX_CONSTRUCT_VERSION=${project.version}
fi

PAX_PLUGIN=org.ops4j.pax.construct:maven-pax-plugin:${PAX_CONSTRUCT_VERSION}

unset REPOSITORYID
unset REPOSITORYURL

while
  getopts i:u:h- SETTING
do
  case ${SETTING} in
    h|\?) echo "pax-add-repository -i repositoryId -u repositoryURL [-- mvnOpts ...]" ; exit ;;

    i) REPOSITORYID=${OPTARG} ;;
    u) REPOSITORYURL=${OPTARG} ;;

    -) break ;;
  esac
done

shift $((${OPTIND}-1))

if [ -z "${REPOSITORYID}" ]
then
  read -p "repositoryId (org.ops4j.repository) ? " REPOSITORYID
fi
if [ -z "${REPOSITORYURL}" ]
then
  read -p "repositoryURL (http://repository.ops4j.org/maven2) ? " REPOSITORYURL
fi

mvn ${PAX_PLUGIN}:add-repository \
  -DrepositoryId=${REPOSITORYID:=org.ops4j.repository} \
  -DrepositoryURL=${REPOSITORYURL:=http://repository.ops4j.org/maven2} \
  ${PAX_CONSTRUCT_OPTIONS} "$@"

