#!/bin/sh
SCRIPTS=`dirname \$0`
. \${SCRIPTS}/pax-validate

if [ -z "\${PAX_CONSTRUCT_VERSION}" ]
then
  PAX_CONSTRUCT_VERSION=${version}
fi

PAX_PLUGIN=org.ops4j.pax.construct.ng:maven-pax-plugin:\${PAX_CONSTRUCT_VERSION}
<%
  options.order.each {
%>
unset ${options[it].name.toUpperCase()}<% } %>

while
  getopts <% options.order.each { %>${it}:<% } %>h- SETTING
do
  case \${SETTING} in
    h|\\?) echo "pax-${mojo}<%
  options.order.each {
    %> <%
    if( options[it].optional ) {
      %>[<%
    }
    %>-${it} ${options[it].name}<%
    if( options[it].optional ) {
      %>]<%
    }
  } %> [-- mvnOpts ...]" ; exit ;;
<%
  options.order.each {
%>
    ${it}) ${options[it].name.toUpperCase()}=\${OPTARG} ;;<% } %>

    -) break ;;
  esac
done

shift \$((\${OPTIND}-1))
<%
  allRequired = true
  allOptional = true
  options.order.each {
    if( options[it].optional )
      allRequired = false
    else
      allOptional = false
  }

  if( !allOptional ) {
%>
<%
    pad = ''
    if( !allRequired ) {
      op = 'if'
      options.order.each {
        if( !options[it].optional ) {
          %>${op} [ -z "\${${options[it].name.toUpperCase()}}" ]<%
          op = ' ||'
        }
      }
%>
then
<%    pad = '  '
    }
    options.order.each {
%>${pad}if [ -z "\${${options[it].name.toUpperCase()}}" ]
${pad}then
${pad}  read -p "${options[it].name} (${options[it].example}) ? " ${options[it].name.toUpperCase()}
${pad}fi
<%
    }
    if( !allRequired ) {
%>fi
<%  }
  }
%>
mvn \${PAX_PLUGIN}:${mojo} \\<%
  options.order.each {
%>
  -D${options[it].name}=\${${options[it].name.toUpperCase()}:=${options[it].example}} \\<% } %>
  \${PAX_CONSTRUCT_OPTIONS} "\$@"

