#!/bin/sh
SCRIPTS=`dirname $0`
. ${SCRIPTS}/pax-validate

unset GROUPID
unset ARTIFACTID
unset VERSION

while
  getopts g:a:v:h- SETTING
do
  case ${SETTING} in
    h|\?) echo "pax-create-project -g groupId -a artifactId [-v version ] [-- mvnopts ...]" ; exit ;;

    g) GROUPID=${OPTARG} ;;
    a) ARTIFACTID=${OPTARG} ;;
    v) VERSION=${OPTARG} ;;

    -) break ;;
  esac
done

shift $((${OPTIND}-1))
EXTRA=$*

if [[ -z "${GROUPID}" || -z "${ARTIFACTID}" ]]
then
  REQUEST_INPUT=true
fi
if [ -z "${GROUPID}" ]
then
  read -p "project groupId (org.ops4j.example) ? " GROUPID
fi
if [ -z "${ARTIFACTID}" ]
then
  read -p "project artifactId (myProject) ? " ARTIFACTID
fi
if [[ -z "${VERSION}" && ${REQUEST_INPUT} ]]
then
  read -p "project version (0.1.0-SNAPSHOT) ? " VERSION
fi

mvn org.ops4j.pax.construct:maven-pax-plugin:0.1.3:create-project \
  -DgroupId=${GROUPID:=org.ops4j.example} \
  -DartifactId=${ARTIFACTID:=myProject} \
  -Dversion=${VERSION:=0.1.0-SNAPSHOT} ${EXTRA}

