#!/bin/sh
SCRIPTS=`dirname $0`
. ${SCRIPTS}/pax-validate

unset GROUPID
unset ARTIFACTID
unset VERSION

while
  getopts g:a:v:h- SETTING
do
  case ${SETTING} in
    h|\?) echo "pax-import-bundle -g groupId -a artifactId -v version [-- mvnopts ...]" ; exit ;;

    g) GROUPID=${OPTARG} ;;
    a) ARTIFACTID=${OPTARG} ;;
    v) VERSION=${OPTARG} ;;

    -) break ;;
  esac
done

shift $((${OPTIND}-1))
EXTRA=$*

if [ -z "${GROUPID}" ]
then
  read -p "bundle groupId (org.ops4j.example) ? " GROUPID
fi
if [ -z "${ARTIFACTID}" ]
then
  read -p "bundle artifactId (myBundle) ? " ARTIFACTID
fi
if [ -z "${VERSION}" ]
then
  read -p "bundle version (0.1.0-SNAPSHOT) ? " VERSION
fi

mvn pax:import-bundle \
  -DgroupId=${GROUPID:=org.ops4j.example} \
  -DartifactId=${ARTIFACTID:=myBundle} \
  -Dversion=${VERSION:=0.1.0-SNAPSHOT} ${EXTRA}

